/**
 * Algoritma Laboratuvarı — kalıp kartları.
 *
 * Deneyimli programcının kafasındaki hazır planlar adlarıyla öğretilir. Bir ünite bitince
 * öğrenciye o ünitenin kalıp kartı gösterilir; sonraki görevlerde ipucu olarak döner. Kartlar
 * sınıflar boyunca geri gelir (sıra 1. sınıftan 8. sınıfa).
 */
import { programKur, type Program } from './program';

export interface KalipKarti {
  id: string;
  ad: string;
  neIseYarar: string;
  ornek: Program;
  ornekAciklama: string;
  yineKarsinaCikacak: string[];
  /** Öğretmen notundaki biçimsel adı */
  bicimselAd: string;
  /** Hangi ünitede kazanılır */
  kazanildigiYer: string;
}

export const KALIPLAR: readonly KalipKarti[] = [
  // --- 1. sınıf -------------------------------------------------------------------
  {
    id: 'sirayla',
    ad: 'Sırayla yap',
    neIseYarar: 'Robot kartları yukarıdan aşağıya, birer birer ve sırayla uygular.',
    ornek: programKur(['ileri', 'ileri', 'ileri'], 'k0-'),
    ornekAciklama: 'Robot üç adımda çiçeğe varır.',
    yineKarsinaCikacak: ['Dönerek bir yere gitmek', 'Önce gidip sonra sulamak', 'Her programda: sıra önemlidir'],
    bicimselAd: 'Sıralı yapı',
    kazanildigiYer: '1. sınıf · Adım adım',
  },
  {
    id: 'don-ve-devam',
    ad: 'Dön ve devam et',
    neIseYarar: 'Robot dönünce yerinde kalır; sonra yeni yöne doğru ilerler.',
    ornek: programKur(['ileri', 'sagaDon', 'ileri'], 'k5-'),
    ornekAciklama: 'Robot köşede sağına döner ve yoluna devam eder.',
    yineKarsinaCikacak: ['Köşeli bahçede saksı sulamak', 'Merdiven yolunda inmek', 'Çizgi robotuyla şekil çizmek'],
    bicimselAd: 'Yön değiştirme (sıralı yapı içinde)',
    kazanildigiYer: '1. sınıf · Sağa, sola',
  },
  {
    id: 'git-ve-yap',
    ad: 'Oraya git, işini yap',
    neIseYarar: 'Önce işin yapılacağı yere gidersin, sonra işi yaparsın.',
    ornek: programKur(['ileri', 'ileri', 'sula'], 'k6-'),
    ornekAciklama: 'Robot saksının karesine varır, sonra sular.',
    yineKarsinaCikacak: ['Domates toplamak', 'Dronla küp koymak', 'Her eylemde: doğru yer, sonra iş'],
    bicimselAd: 'Konumlandırma + eylem',
    kazanildigiYer: '1. sınıf · Git ve sula',
  },
  {
    id: 'oruntu',
    ad: 'Örüntüyü bul',
    neIseYarar: 'Kodda tekrar eden parçayı görürsen kodu kolayca uzatır, bozulduğu yeri hemen bulursun.',
    ornek: programKur(['ileri', 'sula', 'ileri', 'sula'], 'k7-'),
    ornekAciklama: '"ileri, sula" parçası tekrar ediyor.',
    yineKarsinaCikacak: ['2. sınıf: tekrar eden parça "… kez tekrarla" bloğuna girer', 'Çizgi robotuyla desen çizmek'],
    bicimselAd: 'Örüntü (döngüye hazırlık)',
    kazanildigiYer: '1. sınıf · Örüntü',
  },
  // --- 2. sınıf -------------------------------------------------------------------
  {
    id: 'n-kez',
    ad: 'Kaç kez tekrarla',
    neIseYarar: 'Aynı parçayı kaç kez yapacağını biliyorsan onu bir kez yaz, kaç kez tekrarlanacağını söyle.',
    ornek: programKur([['kez', 3, ['ileri', 'sula']]], 'k8-'),
    ornekAciklama: 'Robot 3 kez "ileri git, sula" yapar: üç saksı sulanır.',
    yineKarsinaCikacak: ['Kare çizmek: 4 kez kenar ve dönüş', 'Kule kurmak: 3 kez küp koy', 'Çarpma: 3 kez 2 adım = 6 adım'],
    bicimselAd: 'Sayaçlı döngü',
    kazanildigiYer: '2. sınıf · Kaç kez?',
  },
  {
    id: 'desenli-tekrar',
    ad: 'Desenli tekrar',
    neIseYarar: 'Tekrarın içine birden çok adım koyarsın; desen her turda baştan başlar.',
    ornek: programKur([['kez', 3, ['ileri', 'sagaDon', 'ileri', 'solaDon']]], 'k9-'),
    ornekAciklama: 'Robot merdiven gibi basamak basamak iner.',
    yineKarsinaCikacak: ['Zikzak çizmek', 'Aralıklı saksıları sulamak', 'İç içe tekrar (4. sınıf)'],
    bicimselAd: 'Döngü gövdesi (birden çok komut)',
    kazanildigiYer: '2. sınıf · Tekrar eden yol',
  },
  {
    id: 'en-kisa',
    ad: 'En kısa yolu seç',
    neIseYarar: 'Hedefe giden yolları say ve karşılaştır; en az adımlı olanı seç.',
    ornek: programKur(['ileri', 'ileri', 'sagaDon', 'ileri'], 'k10-'),
    ornekAciklama: 'Çalıların arasından dolaşmak yerine köşeden dönen yol 3 adımdır.',
    yineKarsinaCikacak: ['Kargo dronu: en kısa uçuş', 'Otonom araç: kısa rota', '8. sınıf: koordinatta uzaklık'],
    bicimselAd: 'En kısa yol (eniyileme)',
    kazanildigiYer: '2. sınıf · En kısa yol',
  },
  {
    id: 'katman',
    ad: 'Kat kat kur',
    neIseYarar: 'Yapıyı alttan üste kurarsın; her küp bir öncekinin üstüne gelir.',
    ornek: programKur(['ileri', ['kez', 3, ['koy']]], 'k11-'),
    ornekAciklama: 'Dron bir kare ilerler ve üç katlı bir kule kurar.',
    yineKarsinaCikacak: ['Basamaklı kule (5. sınıf örüntü)', 'Küplerle prizma ve hacim (7. sınıf)'],
    bicimselAd: 'Yapı kurma algoritması',
    kazanildigiYer: '2. sınıf · Küp kule',
  },
  // --- 3. sınıf -------------------------------------------------------------------
  {
    id: 'izle',
    ad: 'Yönergeyi izle',
    neIseYarar: 'Kodu satır satır, robotun yerine geçerek izlersen ne olacağını çalıştırmadan bilirsin.',
    ornek: programKur([['kez', 4, ['ileri', 'sula']]], 'k12-'),
    ornekAciklama: '4 saksı, her biri 2 litre: robot 4 × 2 = 8 litre su harcar.',
    yineKarsinaCikacak: ['Her "Tahmin et" görevinde', 'Değişkenlerin değerini izlemek (5. sınıf)'],
    bicimselAd: 'Kod izleme',
    kazanildigiYer: '3. sınıf · Yönergeyi izle',
  },
  {
    id: 'ayna',
    ad: 'Aynada sağ sola döner',
    neIseYarar: 'Simetrik yarıyı çizerken aynı adımları atarsın; ama sağa dönüşler sola, sola dönüşler sağa döner.',
    ornek: programKur(['ileri', 'ileri', 'solaDon', 'ileri'], 'k13-'),
    ornekAciklama: 'Öbür yarı "ileri, ileri, sağa dön, ileri" ise aynadaki yarı "ileri, ileri, sola dön, ileri"dir.',
    yineKarsinaCikacak: ['Doğruya göre simetri (4. sınıf)', 'Yansıma dönüşümü (7. sınıf)', 'Koordinatta yansıma (8. sınıf)'],
    bicimselAd: 'Yansıma (simetri) ile kod dönüşümü',
    kazanildigiYer: '3. sınıf · Simetriyi tamamla',
  },
  {
    id: 'bitene-kadar',
    ad: 'Bitene kadar tekrarla',
    neIseYarar: 'Kaç kez yapılacağını bilmeden, iş bitene kadar aynı adımları yinelersin.',
    ornek: programKur([['kadar', 'cikistayim', ['ileri']]], 'k1-'),
    ornekAciklama: 'Robot sıra ne kadar uzun olursa olsun çıkışa kadar yürür.',
    yineKarsinaCikacak: ['Otonom araç: hedefe varana kadar sür', 'Depo yettiği sürece sula (7. sınıf)', 'Sayı laboratuvarı: kalan sıfır olana kadar böl'],
    bicimselAd: 'Koşullu döngü',
    kazanildigiYer: '3. sınıf · Bitene kadar',
  },
  {
    id: 'bak-ve-karar-ver',
    ad: 'Bak ve karar ver',
    neIseYarar: 'Her durumda aynı şeyi yapmak yerine önce bakarsın, sonra duruma göre davranırsın.',
    ornek: programKur([['eger', 'toprakKuru', ['sula']]], 'k2-'),
    ornekAciklama: 'Robot her saksıya bakar; yalnız toprağı kuru olanı sular.',
    yineKarsinaCikacak: ['Sayaç: kırmızıysa say (5. sınıf)', 'Her 3. saksıya gübre (6. sınıf)', '9. sınıf: birden çok koşulu "ve", "veya" ile birleştirme'],
    bicimselAd: 'Seçim yapısı (koşullu ifade)',
    kazanildigiYer: '3. sınıf · Bak ve karar ver',
  },
  // --- 4. sınıf -------------------------------------------------------------------
  {
    id: 'dondur',
    ad: 'Dönüşü say',
    neIseYarar: 'Her sağa ya da sola dönüş çeyrek dönüştür (90°, dik açı); dört çeyrek dönüş bir tam tur eder.',
    ornek: programKur([['kez', 2, ['sagaDon']]], 'k14-'),
    ornekAciklama: 'İki çeyrek dönüş yarım turdur: robot arkasına bakar (180°).',
    yineKarsinaCikacak: ['Kare çizerken 4 dönüş: 360°', 'Üç sağa dönüş bir sola dönüştür', 'Yansımada dönüşler yer değiştirir'],
    bicimselAd: 'Açı: dönme miktarı',
    kazanildigiYer: '4. sınıf · Dönüş ve açı',
  },
  {
    id: 'sekil',
    ad: 'Kenar ve dönüş',
    neIseYarar: 'Bir şekli çizmek için kenarı çiz, köşede dön; bunu kenar sayısı kadar tekrarla.',
    ornek: programKur([['kez', 4, ['ileri', 'ileri', 'sagaDon']]], 'k15-'),
    ornekAciklama: 'Kenarı 2 birim olan kare; çevresi 4 × 2 = 8 birim.',
    yineKarsinaCikacak: ['Dikdörtgen: iki çift eş kenar', 'Yan yana kareler (iç içe tekrar)', 'Çevre ve alan (5. sınıf)'],
    bicimselAd: 'Çokgen çizme döngüsü',
    kazanildigiYer: '4. sınıf · Kodla şekil çiz',
  },
  {
    id: 'ic-ice',
    ad: 'Döngü içinde döngü',
    neIseYarar: 'İç döngü, dış döngünün her turunda baştan sona çalışır; toplam tekrar iki sayının çarpımıdır.',
    ornek: programKur([['kez', 3, [['kez', 2, ['koy']], 'ileri']]], 'k16-'),
    ornekAciklama: '3 kule, her birinde 2 küp: 3 × 2 = 6 küp.',
    yineKarsinaCikacak: ['Tarlayı sıra sıra ekmek (5. sınıf)', 'Küplerle prizma: üç iç içe döngü (7. sınıf)'],
    bicimselAd: 'İç içe döngü',
    kazanildigiYer: '4. sınıf · İç içe tekrar',
  },
  {
    id: 'ayna-uzaklik',
    ad: 'Aynaya aynı uzaklık',
    neIseYarar: 'Bir kare simetri doğrusundan kaç kare uzaksa, simetriği de doğrunun öbür yanında o kadar uzaktadır.',
    ornek: programKur(['ileri', 'boya', 'ileri', 'ileri', 'boya'], 'k17-'),
    ornekAciklama: 'Doğrunun solunda 1 kare uzaktaki boyalı karenin simetriği sağında 1 kare uzaktadır.',
    yineKarsinaCikacak: ['Yansıma dönüşümü (7. sınıf)', 'Koordinatta eksenlere göre yansıma (8. sınıf)'],
    bicimselAd: 'Doğruya göre simetri',
    kazanildigiYer: '4. sınıf · Simetri',
  },
  // --- 5. sınıf -------------------------------------------------------------------
  {
    id: 'sayac',
    ad: 'Sayaç',
    neIseYarar: 'Bir şeyi saymak için değişkeni başta 0 yaparsın; her gördüğünde 1 artırırsın.',
    ornek: programKur([['ata', 'sayaç', 0], 'ileri', ['kadar', 'cikistayim', [['eger', 'domatesKirmizi', [['ata', 'sayaç', ['sayaç', '+', 1]]]], 'ileri']]], 'k18-'),
    ornekAciklama: 'Sıra bitince sayaç kaç kırmızı domates olduğunu gösterir.',
    yineKarsinaCikacak: ['Toplayıcı: 1 yerine değeri ekle', 'Her 3. saksıyı bulmak (6. sınıf)', 'Döngünün kaçıncı turda olduğunu tutmak'],
    bicimselAd: 'Sayaç değişkeni',
    kazanildigiYer: '5. sınıf · Sayaç',
  },
  {
    id: 'toplayici',
    ad: 'Toplayıcı',
    neIseYarar: 'Bir toplamı bulmak için değişkeni başta 0 yaparsın; her yeni değeri onun üstüne eklersin.',
    ornek: programKur([['ata', 'toplam', 0], 'ileri', ['kadar', 'cikistayim', [['eger', 'domatesKirmizi', ['topla', ['ata', 'toplam', ['toplam', '+', '@kutle']]]], 'ileri']]], 'k19-'),
    ornekAciklama: 'Sıra bitince toplam, sepetteki domateslerin kütlesidir.',
    yineKarsinaCikacak: ['Harcanan suyu hesaplamak', 'Ortalama: toplam ÷ sayaç', 'En büyüğü bulmak (6. sınıf)'],
    bicimselAd: 'Biriktiren değişken',
    kazanildigiYer: '5. sınıf · Toplayıcı',
  },
  {
    id: 'yilan',
    ad: 'Sıra sıra tara',
    neIseYarar: 'Bir alanı eksiksiz dolaşmak için bir sırayı git, dön, sonraki sırayı ters yönde git.',
    ornek: programKur([['kez', 2, ['ek', 'ileri', 'ek', 'sagaDon', 'ileri', 'sagaDon', 'ek', 'ileri', 'ek', 'solaDon', 'ileri', 'solaDon']]], 'k20-'),
    ornekAciklama: 'Traktörler ve çim biçme robotları tarlayı böyle tarar; ekilen kare sayısı alandır.',
    yineKarsinaCikacak: ['Alan = en × boy', 'Küplerle zemin döşemek (7. sınıf)'],
    bicimselAd: 'Alan tarama (yılan deseni)',
    kazanildigiYer: '5. sınıf · Tarlayı ek',
  },
  {
    id: 'kural',
    ad: 'Değişkenle büyüyen tekrar',
    neIseYarar: 'Tekrar sayısını bir değişkene bağlarsın; değişken her turda değişince desen büyür.',
    ornek: programKur([['ata', 'kat', 1], ['kez', 3, ['ileri', ['kez', 'kat', ['koy']], ['ata', 'kat', ['kat', '+', 1]]]]], 'k21-'),
    ornekAciklama: 'Kuleler 1, 2, 3 küp: kural "her kule bir öncekinden 1 fazla".',
    yineKarsinaCikacak: ['Örüntünün genel terimi (6. sınıf)', 'İkiye katlayan örüntü (8. sınıf)'],
    bicimselAd: 'Örüntü kuralı (değişkenli döngü)',
    kazanildigiYer: '5. sınıf · Örüntünün kuralı',
  },
  // --- 6. sınıf -------------------------------------------------------------------
  {
    id: 'formul',
    ad: 'Formülle genelle',
    neIseYarar: 'Kaç kez tekrar edeceğini bir ifadeyle yazarsın (2 × n gibi); kod her n için çalışır.',
    ornek: programKur([['kez', [2, '×', 'n'], ['ileri']]], 'k22-'),
    ornekAciklama: 'n saksı birer boşlukla dizilmişse robot 2 × n adım atar.',
    yineKarsinaCikacak: ['Örüntünün genel terimi', 'Doğrusal fonksiyon: y = 2x + 1 (8. sınıf)'],
    bicimselAd: 'Cebirsel ifade ile genelleme',
    kazanildigiYer: '6. sınıf · Formüllü algoritma',
  },
  {
    id: 'katlari',
    ad: 'Her k.’da bir',
    neIseYarar: 'Sayacın k’ya bölümünden kalan 0 ise işi yaparsın: her 3. saksı, her 4. gün gibi.',
    ornek: programKur([['ata', 'sıra', 0], ['kez', 6, ['ileri', ['ata', 'sıra', ['sıra', '+', 1]], ['eger', [['sıra', 'mod', 3], '=', 0], ['gubreVer']]]]], 'k23-'),
    ornekAciklama: '3., 6., 9. … saksılar gübre alır: 3’ün katları.',
    yineKarsinaCikacak: ['Ortak kat: hem 2’nin hem 3’ün katı', 'Tek ve çift sayılar', 'Saat ve takvim hesapları'],
    bicimselAd: 'Bölünebilme koşulu (mod)',
    kazanildigiYer: '6. sınıf · Katlar ve bölünebilme',
  },
  {
    id: 'genel-terim',
    ad: 'Genel terim',
    neIseYarar: 'i. adımdaki değeri i ile yazarsın (2 × i − 1 gibi); böylece 100. adımı saymadan bulursun.',
    ornek: programKur([['ata', 'i', 1], ['kez', 3, ['ileri', ['kez', [[2, '×', 'i'], '-', 1], ['koy']], ['ata', 'i', ['i', '+', 1]]]]], 'k24-'),
    ornekAciklama: 'Kuleler 1, 3, 5 küp: i. kulede 2i − 1 küp.',
    yineKarsinaCikacak: ['Doğrusal fonksiyon (8. sınıf)', 'Diziler (12. sınıf)'],
    bicimselAd: 'Örüntünün genel terimi',
    kazanildigiYer: '6. sınıf · Örüntü ve genel terim',
  },
  {
    id: 'en-buyuk',
    ad: 'En büyüğü bul',
    neIseYarar: 'Şimdiye kadarki en büyüğü bir değişkende tutarsın; daha büyüğünü görünce değiştirirsin.',
    ornek: programKur([['ata', 'enBüyük', 0], 'ileri', ['kadar', 'cikistayim', [['eger', ['@kutle', '>', 'enBüyük'], [['ata', 'enBüyük', '@kutle']]], 'ileri']]], 'k25-'),
    ornekAciklama: 'Sıra bitince enBüyük, en ağır domatesin kütlesidir.',
    yineKarsinaCikacak: ['En küçüğü bulmak: > yerine <', 'Sıralama algoritmaları', 'Veri: en yüksek sıcaklık'],
    bicimselAd: 'En büyük değer (maksimum) algoritması',
    kazanildigiYer: '6. sınıf · En büyüğü bul',
  },
  // --- 7. sınıf -------------------------------------------------------------------
  {
    id: 'ifade-yontemleri',
    ad: 'Üç dilde algoritma',
    neIseYarar: 'Aynı algoritmayı adım adım yazı, sözde kod ya da akış şemasıyla anlatabilirsin; üçü de aynı şeyi söyler.',
    ornek: programKur([['kadar', 'cikistayim', ['ileri', ['eger', 'toprakKuru', ['sula']]]]], 'k26-'),
    ornekAciklama: 'Akış şemasında karar bir eşkenar dörtgendir; döngü geri dönen bir oktur.',
    yineKarsinaCikacak: ['Doğrusal fonksiyon problemleri (8. sınıf)', 'Programlama dilleri (9. sınıf)'],
    bicimselAd: 'Algoritma ifade yöntemleri',
    kazanildigiYer: '7. sınıf · Algoritmayı ifade et',
  },
  {
    id: 'sinir',
    ad: 'Yettiği sürece',
    neIseYarar: 'Bir kaynak (su, para, zaman) yettiği sürece tekrar edersin; eşitsizlik bozulunca döngü durur.',
    ornek: programKur([['kadar', ['@depo', '<', 2], ['ileri', 'sula']]], 'k27-'),
    ornekAciklama: '30 litrelik depo, 2 litrelik sulamalar: 2x ≤ 30 ise x en çok 15.',
    yineKarsinaCikacak: ['Bütçeyle alışveriş', 'Pil bitene kadar sürüş', 'Denklem çözümünü deneyerek bulma'],
    bicimselAd: 'Eşitsizlikle sınırlanan döngü',
    kazanildigiYer: '7. sınıf · Denklem ve eşitsizlik',
  },
  {
    id: 'uc-kat',
    ad: 'Üç boyutlu tekrar',
    neIseYarar: 'En, boy ve yükseklik için iç içe döngüler kurarsın; toplam küp sayısı üçünün çarpımıdır (hacim).',
    ornek: programKur([['kez', 3, ['ileri', ['kez', 2, ['koy']]]]], 'k28-'),
    ornekAciklama: 'Bir sıra: 3 kule, her biri 2 küp. Sıraları da bir döngüyle tekrarlarsan hacim = en × boy × yükseklik; küpler tek tek sayılmaz.',
    yineKarsinaCikacak: ['Yüzey alanı', 'Silindirin hacmi (8. sınıf)'],
    bicimselAd: 'Üç katlı iç içe döngü',
    kazanildigiYer: '7. sınıf · Küplerle prizma',
  },
  {
    id: 'yansit',
    ad: 'Yansıt',
    neIseYarar: 'Şeklin her noktasını doğruya aynı uzaklıkta öbür yana taşırsın; başlangıç noktası da yansır, dönüşler yer değiştirir.',
    ornek: programKur(['kalemKaldir', 'ileri', 'ileri', 'kalemIndir', 'ileri', 'solaDon', 'ileri'], 'k29-'),
    ornekAciklama: 'Robot önce kalemi kaldırıp aynadaki başlangıca gider, sonra yansıyan şekli çizer.',
    yineKarsinaCikacak: ['Koordinatta eksenlere göre yansıma (8. sınıf)', 'Orta dikme inşası'],
    bicimselAd: 'Yansıma dönüşümü',
    kazanildigiYer: '7. sınıf · Yansıma',
  },
  // --- 8. sınıf -------------------------------------------------------------------
  {
    id: 'nokta',
    ad: 'Koordinatla git',
    neIseYarar: 'Önce x kadar sağa, sonra y kadar yukarı gidersin; (x, y) noktasına varırsın.',
    ornek: programKur([['kez', 3, ['ileri']], 'solaDon', ['kez', 2, ['ileri']], 'isaretle'], 'k30-'),
    ornekAciklama: 'Robot (0, 0) noktasından (3, 2) noktasına gider ve işaretler.',
    yineKarsinaCikacak: ['Doğrusal fonksiyonun noktaları', 'Öteleme: (x, y) → (x + a, y + b)'],
    bicimselAd: 'Dik koordinat sistemi',
    kazanildigiYer: '8. sınıf · Koordinat düzlemi',
  },
  {
    id: 'egim',
    ad: 'Sağa 1, yukarı m',
    neIseYarar: 'Her adımda 1 sağa ve m yukarı gidersen işaretlediğin noktalar bir doğru üstüne dizilir; m eğimdir.',
    ornek: programKur([['kez', 3, ['isaretle', 'ileri', 'solaDon', 'ileri', 'ileri', 'sagaDon']], 'isaretle'], 'k31-'),
    ornekAciklama: 'y = 2x: x 1 artınca y 2 artar.',
    yineKarsinaCikacak: ['İki doğrunun eğimini karşılaştırmak', 'Doğrusal ilişkiler: depo, fatura, hız'],
    bicimselAd: 'Doğrusal fonksiyon (eğim)',
    kazanildigiYer: '8. sınıf · Doğrusal fonksiyon',
  },
  {
    id: 'komut',
    ad: 'Kendi komutun',
    neIseYarar: 'Tekrar tekrar kullandığın bir parçaya ad verip komut yaparsın; sonra adıyla çağırırsın.',
    ornek: programKur([['tanim', 'KARE', [['kez', 4, ['ileri', 'sagaDon']]]], ['cagir', 'KARE']], 'k32-'),
    ornekAciklama: 'KARE komutu bir kez tanımlanır, istenen yerde çağrılır: aynı şekil ötelenir.',
    yineKarsinaCikacak: ['Büyük problemi parçalara ayırmak', 'Fonksiyonlar (9. sınıf)'],
    bicimselAd: 'Alt program (fonksiyon)',
    kazanildigiYer: '8. sınıf · Öteleme ve yansıma',
  },
  {
    id: 'katla',
    ad: 'İkiye katla',
    neIseYarar: 'Her turda değeri 2 ile çarparsın; n turdan sonra değer 2ⁿ olur.',
    ornek: programKur([['ata', 'kat', 1], ['kez', 4, ['ileri', ['kez', 'kat', ['koy']], ['ata', 'kat', ['kat', '×', 2]]]]], 'k33-'),
    ornekAciklama: 'Kuleler 1, 2, 4, 8 küp: 2⁰, 2¹, 2², 2³.',
    yineKarsinaCikacak: ['Bakteri çoğalması', 'Bilgisayarda bit ve bayt', 'Üstel fonksiyon (10. sınıf)'],
    bicimselAd: 'Üslü artış (2ⁿ)',
    kazanildigiYer: '8. sınıf · Üslü artış',
  },
];

export function kalipBul(id: string): KalipKarti | undefined {
  return KALIPLAR.find((k) => k.id === id);
}
