/**
 * TYMM matematik kazanımları, 1–8. sınıf (scripts/veri/kazanim-metinleri.json dosyasından üretildi; elle düzenlemeyin).
 * Görevler yalnız bu kodlarla etiketlenir (testler denetler).
 */
import type { Kazanim } from './gorev';

export const KAZANIM_LISTESI: Record<string, Kazanim> = {
  'MAT.1.1.1': { kod: 'MAT.1.1.1', metin: 'Rakamları ve 20’ye kadar olan sayıları (20 dâhil), niceliklerin büyüklüklerini temsil etmek için kullanabilme' },
  'MAT.1.1.2': { kod: 'MAT.1.1.2', metin: 'Ögeleri dağınık veya düzenli bir şekilde bulunan bir nesne grubunu sayarken' },
  'MAT.1.1.3': { kod: 'MAT.1.1.3', metin: 'Nesnelerin sıra sayısını gösterebilme' },
  'MAT.1.1.4': { kod: 'MAT.1.1.4', metin: 'İki niceliğin büyüklüğünü “çok”, “daha çok”, “az”, “daha az” veya “eşit” terimleriyle karşılaştırabilme' },
  'MAT.1.1.5': { kod: 'MAT.1.1.5', metin: '100’e kadar ileriye ve 20’den geriye doğru ritmik sayabilme' },
  'MAT.1.1.6': { kod: 'MAT.1.1.6', metin: 'Artan veya azalan sayı ve şekil örüntülerini çözümleyebilme' },
  'MAT.1.1.7': { kod: 'MAT.1.1.7', metin: 'Verilen bir çokluktaki ilişkilerden yararlanarak 20’ye kadar (20 dâhil) olan nesnelerin sayısını tahmin edebilme' },
  'MAT.1.1.8': { kod: 'MAT.1.1.8', metin: 'Standart olmayan uygun ölçme araçları ile nesnelerin uzunluğunu ve tartacağı kütlenin ölçüm sonuçlarını tahmin edebilme' },
  'MAT.1.1.9': { kod: 'MAT.1.1.9', metin: 'Paraların (1 TL, 5 TL, 10 TL, 20 TL, 50 TL, 100 TL ve 200 TL) temsil ettiği büyüklükleri tanıyabilme' },
  'MAT.1.2.1': { kod: 'MAT.1.2.1', metin: 'Günlük yaşamın içerdiği toplama ve çıkarma işlemlerini çözümleyebilme' },
  'MAT.1.2.2': { kod: 'MAT.1.2.2', metin: 'Toplama ve çıkarma işlemlerinin sonuçlarını tahminde bulunarak ve zihinden işlem yaparak muhakeme edebilme' },
  'MAT.1.2.3': { kod: 'MAT.1.2.3', metin: 'Eşit işaretinin anlamını toplama ve çıkarma işlemi bağlamında yorumlayabilme' },
  'MAT.1.2.4': { kod: 'MAT.1.2.4', metin: 'Toplama ve çıkarma işlemlerinin ilişkisini yorumlayabilme' },
  'MAT.1.3.1': { kod: 'MAT.1.3.1', metin: 'Hedefe ulaşmak için mesafeleri ve yönleri içeren yönergeleri çözümleyebilme' },
  'MAT.1.3.2': { kod: 'MAT.1.3.2', metin: 'Nesnelerin eşliğini değerlendirebilme' },
  'MAT.1.4.1': { kod: 'MAT.1.4.1', metin: 'Kategorik veriye dayalı temel veri grubu ile çalışabilme ve veriye dayalı karar' },
  'MAT.2.1.1': { kod: 'MAT.2.1.1', metin: '100’e kadar olan niceliklerin büyüklüklerini temsil etmede sayıların sembolik temsillerinden yararlanabilme' },
  'MAT.2.1.2': { kod: 'MAT.2.1.2', metin: 'İki basamaklı sayıları çözümleyebilme' },
  'MAT.2.1.3': { kod: 'MAT.2.1.3', metin: 'Sayıların sırasını belirleyebilme' },
  'MAT.2.1.4': { kod: 'MAT.2.1.4', metin: 'İleriye ve geriye doğru ritmik sayabilme' },
  'MAT.2.1.5': { kod: 'MAT.2.1.5', metin: 'Sayı ve sayı temsiline dönüşen şekil örüntülerine dayalı çıkarım yapabilme' },
  'MAT.2.1.6': { kod: 'MAT.2.1.6', metin: 'Bir çokluktaki ilişkilerden yararlanarak 50’ye kadar olan nesnelerin sayısını tahmin edebilme' },
  'MAT.2.1.7': { kod: 'MAT.2.1.7', metin: 'Bütün, yarım ve çeyrek arasındaki ilişkiyi çözümleyebilme' },
  'MAT.2.1.8': { kod: 'MAT.2.1.8', metin: 'Paraları değerlerine göre ilişkilendirerek çözümleyebilme' },
  'MAT.2.1.9': { kod: 'MAT.2.1.9', metin: 'Zaman ölçü birimlerini okuyabilme ve yazabilme' },
  'MAT.2.1.10': { kod: 'MAT.2.1.10', metin: 'Standart uzunluk ve kütle ölçme araçlarının ve birimlerinin gerekliliğini yansıtabilme' },
  'MAT.2.1.11': { kod: 'MAT.2.1.11', metin: 'Standart uzunluk ve kütle ölçü birimleri cinsinden uzunlukları ve kütleleri' },
  'MAT.2.2.1': { kod: 'MAT.2.2.1', metin: 'Toplama ve çıkarma işlemleri gerektiren günlük yaşam problemlerini çözebilme' },
  'MAT.2.2.2': { kod: 'MAT.2.2.2', metin: 'Toplama ve çıkarma işlemlerinin sonuçlarını tahminde bulunarak ve zihinden işlem yaparak muhakeme edebilme' },
  'MAT.2.2.3': { kod: 'MAT.2.2.3', metin: 'Toplama ve çıkarma işlemlerinin ilişkisini yorumlayabilme' },
  'MAT.2.2.4': { kod: 'MAT.2.2.4', metin: 'Çarpma ve bölme işlemlerini toplama ve çıkarma işlemlerine dayalı olarak çözümleyebilme' },
  'MAT.2.2.5': { kod: 'MAT.2.2.5', metin: 'Çarpma ve bölme işlemlerinin sonuçlarını muhakeme edebilme' },
  'MAT.2.2.6': { kod: 'MAT.2.2.6', metin: 'Dört işlem bağlamında eşitliğin farklı anlamlarını yorumlayabilme' },
  'MAT.2.3.1': { kod: 'MAT.2.3.1', metin: 'Günlük yaşamda kullanılan nesneleri biçimsel özelliklerine göre geometrik' },
  'MAT.2.3.2': { kod: 'MAT.2.3.2', metin: 'Geometrik cisim modellerini kullanarak yapılar sentezleyebilme' },
  'MAT.2.3.3': { kod: 'MAT.2.3.3', metin: 'Geometrik şekiller kullanarak modeller sentezleyebilme' },
  'MAT.2.3.4': { kod: 'MAT.2.3.4', metin: 'Geometrik cisim ve şekillerin yön, konum veya büyüklükleri değiştiğinde biçimsel özelliklerinin değişmediğini yorumlayabilme' },
  'MAT.2.3.5': { kod: 'MAT.2.3.5', metin: 'Standart olmayan sıvı ölçme araçları ile sıvı miktarını tahmin edebilme' },
  'MAT.2.3.6': { kod: 'MAT.2.3.6', metin: 'Mesafe ve yönleri içerecek şekilde hedefe ulaşmak için uygun stratejilere' },
  'MAT.2.3.7': { kod: 'MAT.2.3.7', metin: 'Verilen şekiller arasından simetrik olanları ayırt edebilme' },
  'MAT.2.4.1': { kod: 'MAT.2.4.1', metin: 'Kategorik veriye dayalı en çok iki veri grubu ile çalışabilme ve veriye dayalı karar verebilme' },
  'MAT.3.1.1': { kod: 'MAT.3.1.1', metin: 'Niceliklerin büyüklüklerine karşılık gelen 1000’e kadar olan sayıların temsillerinden yararlanabilme' },
  'MAT.3.1.2': { kod: 'MAT.3.1.2', metin: '1000’e kadar olan sayıları çözümleyebilme' },
  'MAT.3.1.3': { kod: 'MAT.3.1.3', metin: 'Sayıları sıralayabilme' },
  'MAT.3.1.4': { kod: 'MAT.3.1.4', metin: 'Sayıları ileriye ve geriye doğru ritmik sayabilme' },
  'MAT.3.1.5': { kod: 'MAT.3.1.5', metin: 'Sayıları tek-çift olarak sınıflandırabilme' },
  'MAT.3.1.6': { kod: 'MAT.3.1.6', metin: 'Tek ve çift sayıların toplamlarının tek ya da çift olduğunu belirleyebilme' },
  'MAT.3.1.7': { kod: 'MAT.3.1.7', metin: 'Sayı ve sayı temsiline dönüşen şekil örüntülerine dayalı çıkarım yapabilme' },
  'MAT.3.1.8': { kod: 'MAT.3.1.8', metin: 'Bir çokluktaki ilişkilerden yararlanarak 100’e kadar olan nesnelerin sayısını tahmin edebilme' },
  'MAT.3.1.9': { kod: 'MAT.3.1.9', metin: 'Bütün, yarım ve çeyreğin kesirle gösterimi için modellerden yararlanabilme' },
  'MAT.3.1.10': { kod: 'MAT.3.1.10', metin: 'Bir bütünü eş parçalar oluşturacak şekilde birim kesir olarak çözümleyebilme' },
  'MAT.3.1.11': { kod: 'MAT.3.1.11', metin: 'Bir kesrin payı ile paydası arasındaki ilişkiyi çözümleyebilme' },
  'MAT.3.1.12': { kod: 'MAT.3.1.12', metin: 'Analog ve dijital saatlerde zamanı okuyabilme ve yazabilme' },
  'MAT.3.1.13': { kod: 'MAT.3.1.13', metin: 'Zaman ölçü birimlerini çözümleyebilme' },
  'MAT.3.1.14': { kod: 'MAT.3.1.14', metin: 'Olayların oluş sürelerini tahmin ederek yargıda bulunabilme' },
  'MAT.3.1.15': { kod: 'MAT.3.1.15', metin: 'Uzunluk ve kütle birimleri arasındaki ilişkileri kullanarak bu birimleri kendi içerisinde çözümleyebilme' },
  'MAT.3.1.16': { kod: 'MAT.3.1.16', metin: 'Madenî ve kâğıt paraları değerlerine göre ilişkilendirerek yorumlayabilme' },
  'MAT.3.2.1': { kod: 'MAT.3.2.1', metin: 'Toplama ve çıkarma işlemlerinin sonuçlarını tahminde bulunarak ve zihinden işlem yaparak muhakeme edebilme' },
  'MAT.3.2.2': { kod: 'MAT.3.2.2', metin: 'Toplama ve çıkarma işlemlerini çözümleyebilme' },
  'MAT.3.2.3': { kod: 'MAT.3.2.3', metin: 'Çarpma ve bölme işlemlerinin sonuçlarını muhakeme edebilme' },
  'MAT.3.2.4': { kod: 'MAT.3.2.4', metin: 'Çarpma ve bölme işlemlerini çözümleyebilme' },
  'MAT.3.2.5': { kod: 'MAT.3.2.5', metin: 'Dört işlem gerektiren durumlar için, verilen yönergeleri takip ederek yorumlayabilme' },
  'MAT.3.2.6': { kod: 'MAT.3.2.6', metin: 'Dört işlem gerektiren günlük yaşam problemlerini çözebilme' },
  'MAT.3.2.7': { kod: 'MAT.3.2.7', metin: 'Dört işlem gerektiren problem durumlarını yapılandırabilme' },
  'MAT.3.2.8': { kod: 'MAT.3.2.8', metin: 'Dört işlem bağlamında eşitliğin farklı anlamlarını yorumlayabilme' },
  'MAT.3.3.1': { kod: 'MAT.3.3.1', metin: 'Geometrik cisimlerin özelliklerini yorumlayabilme' },
  'MAT.3.3.2': { kod: 'MAT.3.3.2', metin: 'Kenar sayılarına göre geometrik şekilleri sınıflandırabilme' },
  'MAT.3.3.3': { kod: 'MAT.3.3.3', metin: 'Matematiksel araç ve teknolojileri kullanarak çeşitli geometrik cisimleri ve şekilleri çizebilme' },
  'MAT.3.3.4': { kod: 'MAT.3.3.4', metin: 'Standart olmayan ve standart ölçme araçları ile şekillerin çevre uzunluğunu tahmin edebilme' },
  'MAT.3.3.5': { kod: 'MAT.3.3.5', metin: 'Standart sıvı ölçü birimleri cinsinden sıvı miktarını tahmin edebilme' },
  'MAT.3.3.6': { kod: 'MAT.3.3.6', metin: 'Birden fazla simetri doğrusu olan şekilleri çözümleyebilme' },
  'MAT.3.3.7': { kod: 'MAT.3.3.7', metin: 'Bir parçası verilen simetrik şekli simetri doğrusuna göre yapılandırabilme' },
  'MAT.3.3.8': { kod: 'MAT.3.3.8', metin: 'Yönerge ile yapılandırılan ve bir parçası verilen bir şekli tamamlayarak simetrisini oluşturmaya ilişkin kodlama stratejilerini kullanarak yargıda bulunabilme' },
  'MAT.3.4.1': { kod: 'MAT.3.4.1', metin: 'Kategorik ve sayma ile elde edilen nicel veriye dayalı tek veri grubu ile çalışabilme ve veriye dayalı karar verebilme' },
  'MAT.4.1.1': { kod: 'MAT.4.1.1', metin: 'Niceliklerin büyüklükleri için en fazla altı basamaklı olan sayıların temsillerinden yararlanabilme' },
  'MAT.4.1.2': { kod: 'MAT.4.1.2', metin: 'En fazla altı basamaklı sayıları çözümleyebilme' },
  'MAT.4.1.3': { kod: 'MAT.4.1.3', metin: 'Sayıları sıralayabilme' },
  'MAT.4.1.4': { kod: 'MAT.4.1.4', metin: 'İleriye ve geriye doğru ritmik saymayı yapılandırabilme' },
  'MAT.4.1.5': { kod: 'MAT.4.1.5', metin: 'Artan azalan sayı örüntüleri ve şekil örüntülerindeki değişimi genelleyebilme' },
  'MAT.4.1.6': { kod: 'MAT.4.1.6', metin: 'Basit, bileşik ve tam sayılı kesirleri kullanmak için matematiksel temsillerden yararlanabilme' },
  'MAT.4.1.7': { kod: 'MAT.4.1.7', metin: 'Denk kesirleri kullanmak için matematiksel temsillerden yararlanabilme' },
  'MAT.4.1.8': { kod: 'MAT.4.1.8', metin: 'Birim kesirlerin büyüklük küçüklük ilişkilerini çözümleyebilme' },
  'MAT.4.1.9': { kod: 'MAT.4.1.9', metin: 'Paydaları eşit olan kesirlerin büyüklük küçüklük ilişkilerini çözümleyebilme' },
  'MAT.4.1.10': { kod: 'MAT.4.1.10', metin: 'Bir çokluğun basit kesir kadarını ve bir basit kesir kadarı verilen çokluğun tamamını çözümleyebilme' },
  'MAT.4.1.11': { kod: 'MAT.4.1.11', metin: 'Paydaları eşit kesirlerle toplama ve çıkarma işlemini yapılandırabilme' },
  'MAT.4.1.12': { kod: 'MAT.4.1.12', metin: 'Paydaları eşit kesirlerle toplama ve çıkarma işlemi gerektiren günlük yaşam problemlerini çözebilme' },
  'MAT.4.1.13': { kod: 'MAT.4.1.13', metin: 'Uzunluk ve kütle birimlerinin kendi içerisindeki dönüşümlerini yorumlayabilme' },
  'MAT.4.2.1': { kod: 'MAT.4.2.1', metin: 'Toplama ve çıkarma işlemlerini zihinden yaparak çözümleyebilme' },
  'MAT.4.2.2': { kod: 'MAT.4.2.2', metin: 'En çok dört basamaklı sayılarla toplama ve çıkarma işlemlerini yapılandırabilme' },
  'MAT.4.2.3': { kod: 'MAT.4.2.3', metin: 'Çarpma ve bölme işlemlerinin sonucunu tahmin edebilme' },
  'MAT.4.2.4': { kod: 'MAT.4.2.4', metin: 'Zihinden çözümlenen çarpma ve bölme işlemleri ile bu işlemlerin kısa yollarını yapılandırabilme' },
  'MAT.4.2.5': { kod: 'MAT.4.2.5', metin: 'Çarpma ve bölme işlemlerini çözümleyebilme' },
  'MAT.4.2.6': { kod: 'MAT.4.2.6', metin: 'Dört işlem içeren yönergeler oluşturarak süreci yorumlayabilme' },
  'MAT.4.2.7': { kod: 'MAT.4.2.7', metin: 'Dört işlem gerektiren problemleri çözebilme' },
  'MAT.4.2.8': { kod: 'MAT.4.2.8', metin: 'Dört işlem gerektiren problem durumlarını yapılandırabilme' },
  'MAT.4.2.9': { kod: 'MAT.4.2.9', metin: 'Dört işlem bağlamında eşitliğin farklı anlamlarını yorumlayabilme' },
  'MAT.4.3.1': { kod: 'MAT.4.3.1', metin: 'Geometrik cisimlerin açınımlarını yapılandırabilme' },
  'MAT.4.3.2': { kod: 'MAT.4.3.2', metin: 'Geometrik şekilleri köşe ve kenarlarına göre yorumlayabilme' },
  'MAT.4.3.3': { kod: 'MAT.4.3.3', metin: 'Geometrik şekillerin çevre uzunluğunu ölçmede matematiksel araç ve teknolojiden yararlanabilme' },
  'MAT.4.3.4': { kod: 'MAT.4.3.4', metin: 'Standart olmayan ölçü birimleri cinsinden şekillerin alanlarını tahmin edebilme' },
  'MAT.4.3.5': { kod: 'MAT.4.3.5', metin: 'Günlük yaşamdan örneklerle açıyı bir dönme miktarı olarak yorumlayabilme' },
  'MAT.4.3.6': { kod: 'MAT.4.3.6', metin: 'Açı ölçümüne ilişkin standart ölçme araçlarının gerekliliğini değerlendirebilme' },
  'MAT.4.3.7': { kod: 'MAT.4.3.7', metin: 'Dik açıyı referans alarak açıları dar ve geniş olarak sınıflandırabilme' },
  'MAT.4.3.8': { kod: 'MAT.4.3.8', metin: 'Geometrik nesneler ve şekiller üzerinden doğruya göre simetriyi yorumlayabilme' },
  'MAT.4.3.9': { kod: 'MAT.4.3.9', metin: 'Bir şeklin doğruya göre simetrisini yapılandırabilme' },
  'MAT.4.3.10': { kod: 'MAT.4.3.10', metin: 'Geometrik şekillere dayalı bir yapı oluşturabilmek için kodlama stratejilerini yapılandırabilme' },
  'MAT.4.4.1': { kod: 'MAT.4.4.1', metin: 'Günlük yaşamdan herhangi bir olayın olasılığını “imkânsız, olabilir, kesin” olarak belirleyebilme' },
  'MAT.4.4.2': { kod: 'MAT.4.4.2', metin: 'Kategorik veriye ve sayma ile elde edilen nicel veriye dayalı en çok iki veri grubu ile çalışabilme ve veriye dayalı karar verebilme' },
  'MAT.5.1.1': { kod: 'MAT.5.1.1', metin: 'Altı basamaklı sayıları okuma ve yazmayı çok basamaklı sayılara genelleyebilme' },
  'MAT.5.1.2': { kod: 'MAT.5.1.2', metin: 'Doğal sayılar ve işlemler içeren gerçek yaşam problemlerini çözebilme' },
  'MAT.5.1.3': { kod: 'MAT.5.1.3', metin: 'Gerçek yaşam durumlarına karşılık gelen kesirleri farklı biçimlerde temsil edebilme' },
  'MAT.5.1.4': { kod: 'MAT.5.1.4', metin: 'Farklı gösterimlerle ifade edilen kesirlerin karşılaştırılmasına yönelik çıkarım yapabilme' },
  'MAT.5.2.1': { kod: 'MAT.5.2.1', metin: 'Eşitliğin korunumuna ve işlem özelliklerine yönelik çıkarım yapabilme' },
  'MAT.5.2.2': { kod: 'MAT.5.2.2', metin: 'Karşılaştığı günlük hayat ya da matematiksel durumlarda işlem önceliğini yorumlayabilme' },
  'MAT.5.2.3': { kod: 'MAT.5.2.3', metin: 'Sayı ve şekil örüntülerinin kuralına ilişkin muhakeme yapabilme' },
  'MAT.5.2.4': { kod: 'MAT.5.2.4', metin: 'Temel aritmetik işlem içeren durumlardaki algoritmaları yorumlayabilme' },
  'MAT.5.3.1': { kod: 'MAT.5.3.1', metin: 'Temel geometrik çizimler için matematiksel araç ve teknolojiden yararlanabilme' },
  'MAT.5.3.2': { kod: 'MAT.5.3.2', metin: 'Temel geometrik çizimlere dayalı deneyimlerini yansıtabilme' },
  'MAT.5.3.3': { kod: 'MAT.5.3.3', metin: 'Açıları ölçmek için matematiksel araç ve teknolojiden yararlanabilme' },
  'MAT.5.3.4': { kod: 'MAT.5.3.4', metin: 'Düzlemde iki veya üç doğrunun birbirine göre durumuna bağlı olarak oluşabilecek açılara dair çıkarım yapabilme' },
  'MAT.5.3.5': { kod: 'MAT.5.3.5', metin: 'Çokgenleri düzlemde ardışık olarak kesişen doğruların oluşturduğu kapalı şekiller olarak yorumlayabilme' },
  'MAT.5.3.6': { kod: 'MAT.5.3.6', metin: 'Çokgenlerin özellikleri ile ilgili edindiği deneyimleri yansıtabilme' },
  'MAT.5.3.7': { kod: 'MAT.5.3.7', metin: 'Matematiksel araç ve teknoloji yardımıyla düzlemde iki noktada kesişen çember çiftinin merkezleri ve kesişim noktalarından biri ile inşa edilen üçgenlerin kenar özelliklerine yönelik muhakeme yapabilme' },
  'MAT.5.4.1': { kod: 'MAT.5.4.1', metin: 'Kenar uzunlukları doğal sayı olan bir dikdörtgenin çevre uzunluğu verildiğinde kenar uzunluklarını yorumlayabilme' },
  'MAT.5.4.2': { kod: 'MAT.5.4.2', metin: 'Birim karelerden yola çıkarak dikdörtgenin alanını değerlendirebilme' },
  'MAT.5.4.3': { kod: 'MAT.5.4.3', metin: 'Kenar uzunlukları doğal sayı olan bir dikdörtgenin alanının ölçüsü verildiğinde çevre uzunluğunu, çevre uzunluğu verildiğinde alanını yorumlayabilme' },
  'MAT.5.4.4': { kod: 'MAT.5.4.4', metin: 'Dikdörtgenin çevre uzunluğu ve alanı ile ilgili problemleri çözebilme' },
  'MAT.5.5.1': { kod: 'MAT.5.5.1', metin: 'Kategorik veri ile çalışabilme ve veriye dayalı karar verebilme' },
  'MAT.5.5.2': { kod: 'MAT.5.5.2', metin: 'Başkaları tarafından oluşturulan kategorik veriye dayalı istatistiksel sonuç veya yorumları tartışabilme' },
  'MAT.5.6.1': { kod: 'MAT.5.6.1', metin: 'Herhangi bir olayın olasılığının 0 (imkânsız) ile 1 (kesin) arasında (0 ve 1 dâhil) olduğunu (olasılık spektrumu) yorumlayabilme' },
  'MAT.5.6.2': { kod: 'MAT.5.6.2', metin: 'Olayları az ya da çok olasılıklı şeklinde yapılandırabilme' },
  'MAT.6.1.1': { kod: 'MAT.6.1.1', metin: 'Karşılaştığı problem durumlarında bir doğal sayının çarpan ve katlarına yönelik muhakeme yapabilme' },
  'MAT.6.1.2': { kod: 'MAT.6.1.2', metin: 'Bir doğal sayının 2, 3, 4, 5, 6, 9 ve 10 ile tam bölünebilme kriterlerine ilişkin çıkarım yapabilme' },
  'MAT.6.1.3': { kod: 'MAT.6.1.3', metin: 'Bir doğal sayının asal olma durumunu ve asal çarpanlarını çözümleyebilme' },
  'MAT.6.1.4': { kod: 'MAT.6.1.4', metin: 'Günlük hayat problemleri ya da matematiksel durumlar üzerinden ortak kat ve ortak böleni yorumlayabilme' },
  'MAT.6.1.5': { kod: 'MAT.6.1.5', metin: 'Gerçek yaşam durumlarında ondalık gösterimlerin basamak değerlerini kesirlerden yararlanarak yorumlayabilme' },
  'MAT.6.1.6': { kod: 'MAT.6.1.6', metin: 'Kesir ve bölme işlemi arasındaki ilişkiye yönelik tümevarımsal akıl yürütebilme' },
  'MAT.6.1.7': { kod: 'MAT.6.1.7', metin: 'Karşılaştığı günlük hayat ya da matematiksel durumlarda standart uzunluk ölçme birimlerini değerlendirebilme' },
  'MAT.6.1.8': { kod: 'MAT.6.1.8', metin: 'Gerçek yaşam durumlarında karşılaşılan kesir, ondalık ve yüzde gösterimleri ile ilgili dört işlem gerektiren problemleri çözebilme' },
  'MAT.6.2.1': { kod: 'MAT.6.2.1', metin: 'Gerçek yaşam durumlarında bilinen niceliklerden bilinmeyen niceliklere ilişkin muhakeme yapabilme' },
  'MAT.6.2.2': { kod: 'MAT.6.2.2', metin: 'Sayı ve şekil örüntülerini yorumlayabilme' },
  'MAT.6.2.3': { kod: 'MAT.6.2.3', metin: 'Cebirsel ifadeler içeren durumlardaki algoritmaları yorumlayabilme' },
  'MAT.6.3.1': { kod: 'MAT.6.3.1', metin: 'Düzlemde iki paralel doğru ve bir kesen ile oluşan açıları sınıflandırabilme' },
  'MAT.6.3.2': { kod: 'MAT.6.3.2', metin: 'Matematiksel araç ve teknolojiden yararlanarak iki paralel doğrunun iki kesenle oluşturduğu şekillerin özelliklerine dair çıkarım yapabilme' },
  'MAT.6.3.3': { kod: 'MAT.6.3.3', metin: 'Matematiksel araç ve teknolojiden yararlanarak birbirlerini ortalayan doğru parçalarını köşegen kabul eden dörtgenlere yönelik çıkarım yapabilme' },
  'MAT.6.3.4': { kod: 'MAT.6.3.4', metin: 'Üçgen, yamuk, paralelkenar, eşkenar dörtgen, dikdörtgen ve karenin açıları ile ilgili problemleri çözebilme' },
  'MAT.6.4.1': { kod: 'MAT.6.4.1', metin: 'Uzunluk ve alan ölçme birimleri arasındaki ilişkilerle ilgili analojik akıl yürütebilme' },
  'MAT.6.4.2': { kod: 'MAT.6.4.2', metin: 'Dikdörtgenin alan bağıntısına yönelik deneyimlerini paralelkenar ve üçgenin alan bağıntılarına yansıtabilme' },
  'MAT.6.4.3': { kod: 'MAT.6.4.3', metin: 'Geometrik şekillerin alanları ile modellenen gerçek yaşam durumlarına yönelik problem çözebilme' },
  'MAT.6.4.4': { kod: 'MAT.6.4.4', metin: 'Çemberin uzunluğu ile çap uzunluğu arasındaki ilişkiye yönelik çıkarım yapabilme' },
  'MAT.6.4.5': { kod: 'MAT.6.4.5', metin: 'Çap veya yarıçap uzunluğu verilen bir çemberin uzunluğu ile ilgili problemleri çözebilme' },
  'MAT.6.4.6': { kod: 'MAT.6.4.6', metin: 'Çemberde merkez açının ölçüsü ile gördüğü yayın uzunluğu arasındaki ilişkiye dair tümevarımsal akıl yürütebilme' },
  'MAT.6.5.1': { kod: 'MAT.6.5.1', metin: 'Kategorik veya nicel (kesikli) veri ile çalışabilme ve veriye dayalı karar verebilme' },
  'MAT.6.5.2': { kod: 'MAT.6.5.2', metin: 'Başkaları tarafından oluşturulan kategorik veya nicel (kesikli) veriye dayalı istatistiksel sonuç veya yorumları tartışabilme' },
  'MAT.6.6.1': { kod: 'MAT.6.6.1', metin: 'Bir olayın olasılığını gözleme dayalı tahmin edebilme' },
  'MAT.7.1.1': { kod: 'MAT.7.1.1', metin: 'Gerçek yaşam ya da matematiksel durumlarda doğal sayı, tam sayı ve rasyonel sayıları yorumlayabilme' },
  'MAT.7.1.2': { kod: 'MAT.7.1.2', metin: 'Gerçek yaşam durumlarında rasyonel sayıların ondalık gösterimlerini yansıtabilme' },
  'MAT.7.1.3': { kod: 'MAT.7.1.3', metin: 'Rasyonel sayıların sıralama ve karşılaştırma ilişkilerini yorumlayabilme' },
  'MAT.7.1.4': { kod: 'MAT.7.1.4', metin: 'Rasyonel sayılar ve işlemler içeren gerçek yaşam problemlerini çözebilme' },
  'MAT.7.1.5': { kod: 'MAT.7.1.5', metin: 'Gerçek yaşam durumları üzerinden oran ilişkileri hakkında muhakeme yapabilme' },
  'MAT.7.1.6': { kod: 'MAT.7.1.6', metin: 'Gerçek yaşam durumları üzerinden orantılı durumları yorumlayabilme' },
  'MAT.7.1.7': { kod: 'MAT.7.1.7', metin: 'Gerçek yaşam durumları üzerinden doğru orantılı durumlara ilişkin problemleri çözebilme' },
  'MAT.7.2.1': { kod: 'MAT.7.2.1', metin: 'Gerçek yaşam durumları ya da matematiksel durumlar üzerinden cebirsel ifadelerle toplama, çıkarma ve bir rasyonel sayıyla çarpma işlemlerini yorumlayabilme' },
  'MAT.7.2.2': { kod: 'MAT.7.2.2', metin: 'Birinci dereceden bir bilinmeyenli denklem ve birinci dereceden bir bilinmeyenli eşitsizlik içeren gerçek yaşam problemlerini çözebilme' },
  'MAT.7.2.3': { kod: 'MAT.7.2.3', metin: 'Sayılar ve özelliklerini içeren ispatlara ilişkin matematiksel muhakeme yapabilme' },
  'MAT.7.2.4': { kod: 'MAT.7.2.4', metin: 'Temel aritmetik ve cebirsel ifadelerle işlem içeren durumlardaki süreci algoritma ifade yöntemlerini kullanarak yapılandırabilme' },
  'MAT.7.3.1': { kod: 'MAT.7.3.1', metin: 'Şekillerin yansıma dönüşümü altındaki görüntülerinin oluşturulmasına dair çıkarım yapabilme' },
  'MAT.7.3.2': { kod: 'MAT.7.3.2', metin: 'Yansıma dönüşümündeki deneyimlerini orta dikme ve açıortay inşasına yansıtabilme' },
  'MAT.7.4.1': { kod: 'MAT.7.4.1', metin: 'Eş küplerle oluşturulan yapılar ile görünümleri arasındaki ilişkiyi çözümleyebilme' },
  'MAT.7.4.2': { kod: 'MAT.7.4.2', metin: 'Dikdörtgenler prizmasının yüzey alanını yorumlayabilme' },
  'MAT.7.4.3': { kod: 'MAT.7.4.3', metin: 'Dikdörtgenler prizmasının hacmini eş nesneler aracılığıyla yorumlayabilme' },
  'MAT.7.4.4': { kod: 'MAT.7.4.4', metin: 'Dikdörtgenler prizmasının hacim bağıntısını değerlendirebilme' },
  'MAT.7.4.5': { kod: 'MAT.7.4.5', metin: 'Hacim ölçme birimleri arasındaki ilişkileri değerlendirebilme' },
  'MAT.7.4.6': { kod: 'MAT.7.4.6', metin: 'Günlük hayat durumlarında dikdörtgenler prizmaları ile modellenen cisimlerin yüzey alanı ve hacmine yönelik problem çözebilme' },
  'MAT.7.4.7': { kod: 'MAT.7.4.7', metin: 'Dikdörtgenin, paralelkenarın alanına ve çemberin uzunluğuna ilişkin deneyimlerini dairenin alan bağıntısına yansıtabilme' },
  'MAT.7.4.8': { kod: 'MAT.7.4.8', metin: 'Çemberde merkez açı ve gördüğü yay uzunluğu arasındaki ilişkiden yola çıkarak daire ve daire diliminin alanları arasındaki ilişkiye yönelik analojik akıl yürütebilme' },
  'MAT.7.4.9': { kod: 'MAT.7.4.9', metin: 'Eşkenar dörtgen ve yamuğun alan bağıntılarına dair çıkarım yapabilme' },
  'MAT.7.4.10': { kod: 'MAT.7.4.10', metin: 'Günlük hayat durumlarında daire, daire dilimi, eşkenar dörtgen ve yamuğun alanına ilişkin problem çözebilme' },
  'MAT.7.5.1': { kod: 'MAT.7.5.1', metin: 'Matematiksel araç ve teknolojiden yararlanarak üçgende kenarortayı, açıortayı ve yüksekliği çözümleyebilme' },
  'MAT.7.5.2': { kod: 'MAT.7.5.2', metin: 'Orta dikme inşasına yönelik deneyimlerini üçgende kenarortay inşasına yansıtabilme' },
  'MAT.7.6.1': { kod: 'MAT.7.6.1', metin: 'Kategorik veya nicel (sürekli) veri ile çalışabilme ve veriye dayalı karar verebilme' },
  'MAT.7.6.2': { kod: 'MAT.7.6.2', metin: 'Başkaları tarafından oluşturulan kategorik veya nicel (sürekli) veriye dayalı istatistiksel sonuç veya yorumları tartışabilme' },
  'MAT.7.7.1': { kod: 'MAT.7.7.1', metin: 'Bir olayın ve tümleyeninin olasılığına ilişkin tümevarımsal akıl yürütebilme' },
  'MAT.7.7.2': { kod: 'MAT.7.7.2', metin: 'Aynı deneye ait olayların eşit olasılıklı olma durumlarını değerlendirebilme' },
  'MAT.7.7.3': { kod: 'MAT.7.7.3', metin: 'Olayları ayrık olma ve ayrık olmama durumlarına göre sınıflandırabilme' },
  'MAT.8.1.1': { kod: 'MAT.8.1.1', metin: 'Farklı bağlamlardaki üslü ifadelere, özelliklerine ve üslü ifadelerle yapılan işlemlere ilişkin çıkarım yapabilme' },
  'MAT.8.1.2': { kod: 'MAT.8.1.2', metin: 'Karşılaştığı problem durumlarında kareköklü ifadeler ile ilgili muhakeme yapabilme' },
  'MAT.8.1.3': { kod: 'MAT.8.1.3', metin: 'Sayıların rasyonel ya da irrasyonelliğini değerlendirebilme' },
  'MAT.8.1.4': { kod: 'MAT.8.1.4', metin: 'Gerçek sayıları ve aralıklarını sayı doğrusunda yorumlayabilme' },
  'MAT.8.2.1': { kod: 'MAT.8.2.1', metin: 'Gerçek yaşam durumları üzerinden dik koordinat sistemini çözümleyebilme' },
  'MAT.8.2.2': { kod: 'MAT.8.2.2', metin: 'Gerçek yaşam durumlarındaki doğrusal ilişkileri doğrusal fonksiyonlarla temsil edebilme' },
  'MAT.8.2.3': { kod: 'MAT.8.2.3', metin: 'Dik koordinat sisteminde iki doğrusal fonksiyonun birbirine göre durumuna ilişkin çıkarım yapabilme' },
  'MAT.8.2.4': { kod: 'MAT.8.2.4', metin: 'Doğrusal fonksiyonlara ilişkin problemlerin çözümlerini algoritma ifade yöntemlerini kullanarak yapılandırabilme' },
  'MAT.8.3.1': { kod: 'MAT.8.3.1', metin: 'Matematiksel araç ve teknoloji yardımıyla üçgenin kenarları ve açıları arasındaki ilişkiyi yorumlayabilme' },
  'MAT.8.3.2': { kod: 'MAT.8.3.2', metin: 'Matematiksel araç ve teknoloji yardımıyla üçgenin kenar uzunlukları arasındaki ilişkiye yönelik çıkarım yapabilme' },
  'MAT.8.3.3': { kod: 'MAT.8.3.3', metin: 'Bir üçgene eş üçgen oluşturmak için üçgenle ilgili bilinmesi yeterli olan elemanlara dair çıkarım yapabilme' },
  'MAT.8.3.4': { kod: 'MAT.8.3.4', metin: 'Bir üçgene benzer üçgen oluşturmak için üçgenle ilgili bilinmesi yeterli olan elemanlara dair çıkarım yapabilme' },
  'MAT.8.3.5': { kod: 'MAT.8.3.5', metin: 'Kenar uzunlukları a²+ b²= c² eşitliğini sağlayan üçgenleri oluşturarak dik üçgen olduklarını; dik üçgenlerde dik kenar uzunluklarının kareleri toplamının hipotenüs uzunluğunun karesine eşit olduğunu yorumlayabilme' },
  'MAT.8.3.6': { kod: 'MAT.8.3.6', metin: 'Üçgende açı-kenar ilişkisi, üçgen eşitsizliği ve Pisagor bağıntısını içeren problemleri çözebilme' },
  'MAT.8.4.1': { kod: 'MAT.8.4.1', metin: 'Dik prizmalar, dikdörtgen dik piramit, dik dairesel silindir ve dik dairesel koninin yüzey açınımlarını çözümleyebilme' },
  'MAT.8.4.2': { kod: 'MAT.8.4.2', metin: 'Dik dairesel silindirin yüzey açınımına ilişkin deneyimlerini dik dairesel silindirin yüzey alanına yansıtabilme' },
  'MAT.8.4.3': { kod: 'MAT.8.4.3', metin: 'Dairenin alan bağıntısının oluşturulma sürecinden hareketle dik dairesel silindirin hacim bağıntısına yönelik analojik akıl yürütebilme' },
  'MAT.8.5.1': { kod: 'MAT.8.5.1', metin: 'Matematiksel araç ve teknoloji yardımıyla öteleme dönüşümünü çözümleyebilme' },
  'MAT.8.5.2': { kod: 'MAT.8.5.2', metin: 'Dik koordinat sisteminde geometrik şekillere ait noktaların apsis ve ordinatlarının öteleme dönüşümündeki değişimlerine ve eksenlere göre yansıma dönüşümündeki değişimlerine ilişkin çıkarım yapabilme' },
  'MAT.8.5.3': { kod: 'MAT.8.5.3', metin: 'Öteleme ve yansıma dönüşümlerini içeren problemleri çözebilme' },
  'MAT.8.6.1': { kod: 'MAT.8.6.1', metin: 'Kategorik veya nicel (kesikli-sürekli) veri ile çalışabilme ve veriye dayalı karar verebilme' },
  'MAT.8.6.2': { kod: 'MAT.8.6.2', metin: 'Başkaları tarafından oluşturulan kategorik veya nicel (kesikli-sürekli) veriye dayalı istatistiksel sonuç veya yorumları tartışabilme' },
  'MAT.8.7.1': { kod: 'MAT.8.7.1', metin: 'Gerçek yaşamda karşılaşabileceği bir olayın olasılığına ilişkin farklı olasılık yaklaşımlarından (öznel, deneysel, teorik) uygun olanı belirleyerek karar verebilme' },
};
